# Generated by Django 4.2.13 on 2025-11-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_customer_is_supplier_store_order_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('from_branch', models.ForeignKey(blank=True, limit_choices_to={'is_shop': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='main.customer')),
                ('to_branch', models.ForeignKey(blank=True, limit_choices_to={'is_shop': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TransferOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='main.item')),
                ('transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.transferorder')),
            ],
        ),
    ]
