# Generated by Django 4.2.13 on 2025-11-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_transferorder_transferorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_shop': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_orders', to='main.customer'),
        ),
    ]
