# Generated by Django 4.2.13 on 2025-11-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_order_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(limit_choices_to={'is_shop': True}, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='main.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock', to='main.item')),
            ],
            options={
                'unique_together': {('branch', 'item')},
            },
        ),
    ]
